### ISSUE TITLE
Unimplemented capability StorageImageWriteWithoutFormat

### ISSUE THREAD

**Issue by kpet** [talvos/talvos#5]
Can't call `vkCreateShaderModule` on a SPIR-V module using this capability. I can provide a sample module produced using clspv or OpenCL C source if that helps.

**Comment by jrprice** [comment]
Is this something from the OpenCL CTS? If so it'd be great if you could point me at the test(s) in question.

I think this feature might just work, so it might just be a case of adding the capability to accepted list if we can verify that some codes using it just work.

**Comment by kpet** [comment]
No, this comes from a very simple test program I've written that I'm using to bring up minimal image support in clvk (so won't be able to confirm that it works before I progress further) but I think clspv in its current form will always require it in modules that have kernels using write_only images.

**Comment by jrprice** [comment]
Found some tests in the Vulkan CTS which cover this and they pass for the formats which Talvos already supports, so I've enabled this capability (as well as the corresponding `read` version).

**Comment by kpet** [comment]
Thanks! I'll let you know if I find issues.
